DROP TABLE IF EXISTS app_user;

CREATE TABLE app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(320) NOT NULL,
  name VARCHAR(255),
  password_hash VARCHAR(255),
  prov_pw_hash VARCHAR(255),
  email_conf_time TIMESTAMP NULL,
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  version INT DEFAULT 0 NOT NULL,
  reset_token VARCHAR(255),
  reset_token_expiry TIMESTAMP
);

-- coluna derivada para email em minúsculas
ALTER TABLE app_user
  ADD COLUMN IF NOT EXISTS email_lower VARCHAR(320)
  GENERATED ALWAYS AS (LOWER(email));

-- evita confusão com "IF NOT EXISTS" no H2 2.x
DROP INDEX IF EXISTS ux_app_user_email_lower;
CREATE UNIQUE INDEX ux_app_user_email_lower ON app_user(email_lower);