-- USER_COMPANY (vínculo usuário–empresa com admin e soft delete)
CREATE TABLE IF NOT EXISTS user_company (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version            INTEGER NOT NULL DEFAULT 0,
    creation_date      TIMESTAMP NOT NULL DEFAULT NOW(),
    update_date        TIMESTAMP NOT NULL DEFAULT NOW(),

    created_by_user_id BIGINT NULL REFERENCES app_user(id),
    user_id            BIGINT NOT NULL REFERENCES app_user(id),
    company_id         BIGINT NOT NULL REFERENCES company(id),

    admin              BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at         TIMESTAMP NULL,

    CONSTRAINT uq_user_company UNIQUE (user_id, company_id)
);

DROP TRIGGER IF EXISTS set_user_company_updated_at ON user_company;
CREATE TRIGGER set_user_company_updated_at
BEFORE UPDATE ON user_company
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Índices úteis (ignoram soft-deleted)
CREATE INDEX IF NOT EXISTS idx_user_company_user_active
  ON user_company (user_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_user_company_company_active
  ON user_company (company_id) WHERE deleted_at IS NULL;