-- PERSON (pessoas da empresa)
-- person_type: 'FISICA' | 'JURIDICA' | 'ESTRANGEIRA'
-- document_type: 'CPF' | 'CNPJ' | 'PASSPORT'
CREATE TABLE IF NOT EXISTS person (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER NOT NULL DEFAULT 0,
    creation_date     TIMESTAMP NOT NULL DEFAULT NOW(),
    update_date       TIMESTAMP NOT NULL DEFAULT NOW(),

    created_by_user_id BIGINT NULL REFERENCES app_user(id),
    company_id         BIGINT NOT NULL REFERENCES company(id),

    person_type       VARCHAR(16)   NOT NULL,
    document_type     VARCHAR(16)   NULL,
    document          VARCHAR(150)  NULL,
    name              VARCHAR(150)  NOT NULL,
    phone             VARCHAR(40)   NULL,
    email             VARCHAR(254)  NULL,

    cep               VARCHAR(16)   NULL,
    uf                VARCHAR(2)    NULL,
    city              VARCHAR(80)   NULL,
    district          VARCHAR(80)   NULL,
    street            VARCHAR(120)  NULL,
    number            VARCHAR(20)   NULL,
    complement        VARCHAR(120)  NULL,

    note              TEXT          NULL
);

-- Unicidade por documento dentro da empresa (ignora nulos)
CREATE UNIQUE INDEX IF NOT EXISTS uq_person_company_doc
  ON person (company_id, document_type, document)
  WHERE document IS NOT NULL;

-- Índices de busca
CREATE INDEX IF NOT EXISTS idx_person_company_name
  ON person (company_id, name);

DROP TRIGGER IF EXISTS set_person_updated_at ON person;
CREATE TRIGGER set_person_updated_at
BEFORE UPDATE ON person
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ANIMAL (pertence a uma PERSON como tutor)
-- animal_type: 'CACHORRO','GATO','COELHO','AVE','REPTIL', etc.
CREATE TABLE IF NOT EXISTS animal (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER NOT NULL DEFAULT 0,
    creation_date     TIMESTAMP NOT NULL DEFAULT NOW(),
    update_date       TIMESTAMP NOT NULL DEFAULT NOW(),

    tutor_id          BIGINT NOT NULL REFERENCES person(id),
    created_by_user_id BIGINT NULL REFERENCES app_user(id),

    name              VARCHAR(100)  NOT NULL,
    animal_type       VARCHAR(32)   NOT NULL,
    note              TEXT          NULL
);

CREATE INDEX IF NOT EXISTS idx_animal_tutor ON animal (tutor_id);
CREATE INDEX IF NOT EXISTS idx_animal_name  ON animal (name);

DROP TRIGGER IF EXISTS set_animal_updated_at ON animal;
CREATE TRIGGER set_animal_updated_at
BEFORE UPDATE ON animal
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();