-- ATTENDANCE (agendamento e realização)
CREATE TABLE IF NOT EXISTS attendance (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version            INTEGER NOT NULL DEFAULT 0,
    creation_date      TIMESTAMP NOT NULL DEFAULT NOW(),
    update_date        TIMESTAMP NOT NULL DEFAULT NOW(),

    animal_id          BIGINT NOT NULL REFERENCES animal(id),
    created_by_user_id BIGINT NULL REFERENCES app_user(id),

    scheduled_at       TIMESTAMP NULL,  -- data/hora de agendamento (futuro)
    appointment_at     TIMESTAMP NULL,  -- data/hora efetiva da consulta
    description        TEXT      NULL
);

-- Índice por animal e ordem temporal (usa appointment se existir, senão scheduled)
CREATE INDEX IF NOT EXISTS idx_attendance_animal_time
  ON attendance (animal_id, COALESCE(appointment_at, scheduled_at));

DROP TRIGGER IF EXISTS set_attendance_updated_at ON attendance;
CREATE TRIGGER set_attendance_updated_at
BEFORE UPDATE ON attendance
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();